# This is a basic workflow to help you get started with Actions

name: Build Taiga Installer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  arch: x64

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Git Apply to Taiga
        working-directory: ./taiga
        run: git apply ../coba.patch

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Cache dependency build
        # id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-deps-build
        with:
          path: |
            taiga\build
            taiga\bin\${{ env.arch }}\Release
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.arch }}-${{ hashFiles('taiga\deps\build.bat') }}

      - name: Build dependencies
        run: taiga\deps\build.bat --machine=$env:arch

      - name: Put git commit hash in version value
        run: |
          (
              Get-Content -Path taiga\src\taiga\config.h
          ) -Replace (
              "(?<=#define TAIGA_VERSION_BUILD 0x).*",
              (git rev-parse --short HEAD)
          ) | Set-Content -Path taiga\src\taiga\config.h

      - name: Print config.h
        run: Get-Content -Path taiga\src\taiga\config.h

      - name: Build Taiga
        run: msbuild "taiga\project\vs2022\Taiga.sln" /m /p:Configuration=Release /p:Platform=$env:arch

      - name: Build installer
        run: makensis /DMACHINE=$env:arch "taiga\setup\Taiga.nsi"

      - uses: actions/upload-artifact@v3
        name: Uploading artifact
        with:
          name: build
          path: |
            taiga/bin/${{ env.arch }}/TaigaSetup.exe

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Download artifacts
  #     uses: actions/download-artifact@v2

  #   - name: Publish release
  #     uses: marvinpinto/action-automatic-releases@v1.2.1
  #     with:
  #       repo_token: "${{secrets.GITHUB_TOKEN}}"
  #       automatic_release_tag: latest
  #       prerelease: true
  #       files: build/TaigaSetup.exe