# This is a basic workflow to help you get started with Actions

name: Build Taiga Installer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build dependencies
        run: .\taiga\deps\build.bat

      - name: Build Taiga
        run: devenv taiga\project\vs2022\Taiga.sln /Build "Release|x86"

      - name: Build installer
        run: "%ProgramFiles(x86)%\NSIS\makensis.exe" /DMACHINE=x86 taiga\setup\Taiga.nsi

      - name: list directory
        run: ls taiga
